version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - |
        terraform init \
          -backend-config="role_arn=arn:aws:iam::$CLIENT_AWS_ACCOUNT_ID:role/xilution-developer-role" \
          -backend-config="key=terraform.tfstate" \
          -backend-config="bucket=xilution-terraform-backend-state-bucket-$CLIENT_AWS_ACCOUNT_ID" \
          -backend-config="dynamodb_table=xilution-terraform-backend-lock-table"
  build:
    commands:
      - |
        terraform apply \
          -var="organization_id=$XILUTION_ORGANIZATION_ID" \
          -auto-approve
  post_build:
    commands:
      - unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
