version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - git config --global url."https://$XILUTION_GITHUB_TOKEN:@github.com/".insteadOf "https://github.com/"
      - |
        terraform init \
          -backend-config="role_arn=arn:aws:iam::$CLIENT_AWS_ACCOUNT:role/xilution-developer-role" \
          -backend-config="key=terraform.tfstate" \
          -backend-config="bucket=xilution-terraform-backend-state-bucket-$CLIENT_AWS_ACCOUNT" \
          -backend-config="dynamodb_table=xilution-terraform-backend-lock-table"
  build:
    commands:
      - |
        terraform apply \
          -var="organization_id=$XILUTION_ORGANIZATION_ID" \
          -var="client_aws_account=$CLIENT_AWS_ACCOUNT" \
          -auto-approve
